// Define your context in this file and it will take precedence over the one
// generated by the UI.
//
// To give (temporary) precedence back to the UI, export "enabled" = false.

exports.enabled = true;
exports.profile = null;
exports.subject = null;
exports.augment = false;
exports.params = null;
